import type { RawSeriesData } from '@tanuki-temaki/shared';

/**
 * Mock series data based on real popular anime
 * This simulates what would be extracted from Crunchyroll
 */
export const mockSeriesData: RawSeriesData[] = [
  {
    provider: 'crunchyroll',
    mediaType: 'ANIME',
    externalId: 'GY8VEQ95Y',
    url: 'https://www.crunchyroll.com/series/GY8VEQ95Y/spy-x-family',
    title: 'SPY x FAMILY',
    titleImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/a249096c7812deb8c3c2c907173f3774.jpg',
    description: 'World-renowned spy Twilight must get married and have a kid in order to execute a critical mission. Totally unprepared for a family, he decides to reach out to a local orphanage to adopt a kid. But the kid he adopts is no ordinary kid. She is a telepath who can read minds. And the woman he chooses for a wife is an assassin. This is the story of a spy who must create a fake family to execute a mission. But no one knows the other\'s secret.',
    rating: 4.8,
    ageRating: 'TV-14',
    languages: ['ja-JP', 'en-US'],
    genres: ['Action', 'Comedy', 'Shounen'],
    contentAdvisory: ['Violence', 'Language'],
    metadata: { episodes: 25 },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'ANIME',
    externalId: 'GRDKJZ81Y',
    url: 'https://www.crunchyroll.com/series/GRDKJZ81Y/demon-slayer',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    titleImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/3f283002b47c62b1e5d311c45f95c97e.jpg',
    description: 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a demon slayer so that he can turn his sister back into a human and kill the demon that massacred his family.',
    rating: 4.9,
    ageRating: 'TV-14',
    languages: ['ja-JP', 'en-US'],
    genres: ['Action', 'Adventure', 'Supernatural', 'Shounen'],
    contentAdvisory: ['Violence', 'Fear'],
    metadata: { episodes: 63 },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'ANIME',
    externalId: 'GR49G9VP6',
    url: 'https://www.crunchyroll.com/series/GR49G9VP6/my-hero-academia',
    title: 'My Hero Academia',
    titleImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/a249096c7812deb8c3c2c907173f3774.jpg',
    description: 'Izuku has dreamt of being a hero all his life—a lofty goal for anyone, but especially challenging for a kid with no superpowers. That\'s right, in a world where eighty percent of the population has some kind of super-powered "quirk," Izuku was unlucky enough to be born completely normal. But that\'s not enough to stop him from enrolling in one of the world\'s most prestigious hero academies.',
    rating: 4.7,
    ageRating: 'TV-14',
    languages: ['ja-JP', 'en-US'],
    genres: ['Action', 'Adventure', 'Shounen'],
    contentAdvisory: ['Violence'],
    metadata: { episodes: 150 },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'ANIME',
    externalId: 'GY3VKX1MR',
    url: 'https://www.crunchyroll.com/series/GY3VKX1MR/jujutsu-kaisen',
    title: 'JUJUTSU KAISEN',
    titleImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/9b2dbb4f93b5c9b1fd67e8d87300e5e4.jpg',
    description: 'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.',
    rating: 4.9,
    ageRating: 'TV-MA',
    languages: ['ja-JP', 'en-US'],
    genres: ['Action', 'Supernatural', 'Shounen'],
    contentAdvisory: ['Violence', 'Gore', 'Fear'],
    metadata: { episodes: 47 },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'ANIME',
    externalId: 'GYQ4MKDZ6',
    url: 'https://www.crunchyroll.com/series/GYQ4MKDZ6/kaguya-sama-love-is-war',
    title: 'Kaguya-sama: Love is War',
    titleImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/2e00efa9c8d1cdfbb0719d6c18a6c6f3.jpg',
    description: 'Considered a genius due to having the highest grades in the country, Miyuki Shirogane leads the prestigious Shuchiin Academy\'s student council as its president, working alongside the beautiful and wealthy vice president Kaguya Shinomiya. The two are often regarded as the perfect couple by students despite them not being in any sort of romantic relationship. However, the truth is that after spending so much time together, the two have developed feelings for one another; unfortunately, neither is willing to confess, as doing so would be a sign of weakness. With their pride as elite students on the line, Miyuki and Kaguya embark on a quest to do whatever is necessary to get a confession out of the other.',
    rating: 4.8,
    ageRating: 'TV-14',
    languages: ['ja-JP', 'en-US'],
    genres: ['Comedy', 'Romance', 'School'],
    contentAdvisory: [],
    metadata: { episodes: 37 },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'ANIME',
    externalId: 'G8DHV7W21',
    url: 'https://www.crunchyroll.com/series/G8DHV7W21/chainsaw-man',
    title: 'Chainsaw Man',
    titleImage: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/8b77c43e3c0e3a6d403cb1f0e7e412da.jpg',
    description: 'Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses with Pochita. One day, Denji is betrayed and killed. As his consciousness fades, he makes a contract with Pochita and gets revived as "Chainsaw Man" — a man with a devil\'s heart.',
    rating: 4.7,
    ageRating: 'TV-MA',
    languages: ['ja-JP', 'en-US'],
    genres: ['Action', 'Supernatural', 'Shounen'],
    contentAdvisory: ['Violence', 'Gore', 'Sexual Themes'],
    metadata: { episodes: 12 },
  },
  // Manga entries
  {
    provider: 'crunchyroll',
    mediaType: 'MANGA',
    externalId: 'anilist-21480',
    url: 'anilist://21480',
    title: 'Berserk',
    titleImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30002-7EzO7o21jzeF.jpg',
    description: 'Guts, a former mercenary now known as the "Black Swordsman," is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings.',
    rating: 4.9,
    ageRating: 'R+',
    languages: ['ja-JP'],
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Horror', 'Seinen'],
    contentAdvisory: ['Violence', 'Gore', 'Sexual Themes'],
    metadata: {
      anilistId: 30002,
      chapters: 380,
      volumes: 42,
      streamingLinks: {},
    },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'MANGA',
    externalId: 'anilist-30656',
    url: 'anilist://30656',
    title: 'Vinland Saga',
    titleImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30656-53B7FAy8SnHA.jpg',
    description: 'Thorfinn is the son to one of the Vikings\' greatest warriors, but when his father is killed in battle by the mercenary leader Askeladd, he swears to have his revenge. Thorfinn joins Askeladd\'s band in order to challenge him to a duel, and ends up caught in the middle of a war for the crown of England.',
    rating: 4.8,
    ageRating: 'R',
    languages: ['ja-JP'],
    genres: ['Action', 'Adventure', 'Drama', 'Historical', 'Seinen'],
    contentAdvisory: ['Violence', 'Gore'],
    metadata: {
      anilistId: 30656,
      chapters: 214,
      volumes: 28,
      streamingLinks: {},
    },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'MANGA',
    externalId: 'anilist-30656',
    url: 'anilist://656',
    title: 'Vagabond',
    titleImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx656-Bbnw58saHTQd.png',
    description: 'In 16th century Japan, Shinmen Takezou is a wild, rough young man, in both his appearance and his actions. His aggressive nature has won him the collective reproach and fear of his village, leading him and his best friend, Matahachi Honiden, to run away in search of something grander than provincial life. The pair enlist in the Toyotomi army, yearning for glory—but when the Toyotomi suffer a crushing defeat at the hands of the Tokugawa Clan at the Battle of Sekigahara, the friends barely make it out alive.',
    rating: 4.9,
    ageRating: 'R',
    languages: ['ja-JP'],
    genres: ['Action', 'Adventure', 'Drama', 'Historical', 'Seinen'],
    contentAdvisory: ['Violence'],
    metadata: {
      anilistId: 656,
      chapters: 327,
      volumes: 37,
      streamingLinks: {},
    },
  },
  {
    provider: 'crunchyroll',
    mediaType: 'MANGA',
    externalId: 'anilist-86310',
    url: 'anilist://86310',
    title: 'Fire Force',
    titleImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86310-HjLEkQJKz7tK.jpg',
    description: 'Terror has paralyzed the clockwork metropolis of Tokyo! Possessed by demons, people have begun to burst into flame, leading to the establishment of a special firefighting team: the Fire Force, ready to roll on a moment\'s notice to fight spontaneous combustion anywhere it might break out. The team is about to get a unique addition. Shinra, a boy who possesses the power to run at the speed of a rocket, leaving behind the famous "devil\'s footprints" and destroying his shoes in the process. Can Shinra and his colleagues discover the source of this strange epidemic before the city burns to ashes?',
    rating: 4.6,
    ageRating: 'R',
    languages: ['ja-JP'],
    genres: ['Action', 'Supernatural', 'Shounen'],
    contentAdvisory: ['Violence'],
    metadata: {
      anilistId: 86310,
      chapters: 304,
      volumes: 34,
      streamingLinks: {},
    },
  },
];
